language: swift

osx_image: xcode11.2
env:
  matrix:
    - TEST_SDK=iphonesimulator13.2 OS=15.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.2 OS=15.1 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project Calculator.xcodeproj -scheme Calculator -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
